In [1]:
import numpy as np

In [3]:
a=np.array([1,4,5,8,6,3,9,7,2],int).reshape(-1,3)
a

array([[1, 4, 5],
       [8, 6, 3],
       [9, 7, 2]])

가로로 쓴다는 것을 알 수 있다.

In [5]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

slicing

In [65]:
a[1,:]

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [66]:
a[1][:]

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
b

In [53]:
a=np.array([[[0,1,2,3],[4,5,6,7]],[[10,11,12,13],[14,15,16,17]],[[20,21,22,23],[24,25,26,27]]])

In [16]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27]]])

In [15]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 11, 12, 13, 14, 15, 16, 17, 20,
       21, 22, 23, 24, 25, 26, 27])

3차원의 인덱스는 z,y,x

In [19]:
a[0,:,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
a[:,0,:]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [21]:
a[:,:,0]

array([[ 0,  4],
       [10, 14],
       [20, 24]])

3차원 차원별 계산 계산

In [63]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27]]])

In [64]:
a.shape

(3, 2, 4)

z방향으로 누르기

In [33]:
a.sum(0)

array([[30, 33, 36, 39],
       [42, 45, 48, 51]])

In [37]:
a.mean(0)

array([[10., 11., 12., 13.],
       [14., 15., 16., 17.]])

y방향으로 누르기

In [35]:
a.sum(1)

array([[ 4,  6,  8, 10],
       [24, 26, 28, 30],
       [44, 46, 48, 50]])

In [39]:
a.mean(1)

array([[ 2.,  3.,  4.,  5.],
       [12., 13., 14., 15.],
       [22., 23., 24., 25.]])

x방향으로 누르기

In [36]:
a.sum(2)

array([[  6,  22],
       [ 46,  62],
       [ 86, 102]])

In [40]:
a.mean(2)

array([[ 1.5,  5.5],
       [11.5, 15.5],
       [21.5, 25.5]])

argmax, argmin

In [54]:
np.argmax(a)  #ind23가 가장크다

23

In [56]:
np.argmax(a,axis=0)  # z방향으로 따졌을 때 가장 큰 값이 있는 인덱스

array([[2, 2, 2, 2],
       [2, 2, 2, 2]], dtype=int64)

In [60]:
np.argmax(a,axis=1)  # y방향으로 따졌을 때 가장 큰 값이 있는 인덱스

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [59]:
np.argmax(a,axis=2)  # x방향으로 따져씅ㄹ 때 가장 큰 값이 있는 인덱스

array([[3, 3],
       [3, 3],
       [3, 3]], dtype=int64)

행렬 만들기

In [23]:
np.arange(0,21,4)

array([ 0,  4,  8, 12, 16, 20])

In [24]:
np.arange(0,20,4)  #a부터 b전까지 c단위로

array([ 0,  4,  8, 12, 16])

In [27]:
np.linspace(0,20,3)  # a부터 까지 c등분

array([ 0., 10., 20.])

In [28]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones((5,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

행렬 붙이기   np는 hstack  vstack을 쓰는게 차원 헷갈림 방지에 좋다

In [41]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [42]:
np.hstack((a,b)) # 수평방향으로 붙이기

array([1, 2, 3, 4, 5, 6])

In [43]:
np.vstack((a,b))  # 수직방향으로 붙이기

array([[1, 2, 3],
       [4, 5, 6]])

비교

In [52]:
a!=2

array([ True, False,  True])

인덱스

ValueError: cannot reshape array of size 30 into shape (4,3)

In [51]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])